theme = "congo"
#baseURL = "https://whits.io"
title = "whits.io"
languageCode = "en-US"
languageName = "English"
weight = 1

[params]
    description = "Whit Huntley's Blog & About"

[params.author]
name = "Whit Huntley"
image = "imgs/professionalA-tiny.jpg"
headline = "**[*she/her*]** - Building systems that outlast fads, empower teams, and scale fearlessly."
bio = "Developer, operator, over-engineerer. I have been banging my head against computers in one capacity or another since the age of 13."
links = [
    { email = "mailto:hello@whits.io"},
    { github = "https://github.com/whit-colm"},
    { linkedin = "https://linkedin.com/in/whit-colm"},
    { bluesky = "https://bsky.app/profile/did:plc:jeptbfcktk2a2f4myjzqyrs3" }
]