theme = "congo"
#baseURL = "https://whits.io"
title = "whits.io"
languageCode = "en-US"
languageName = "English"
weight = 1

[params]
    description = "Whit Huntley's Web Hole"

[params.author]
name = "Whit Huntley"
image = "imgs/professionalA-tiny.jpg"
headline = "**[*she/her*]** - Building systems that outlast fads, empower teams, and scale fearlessly."
bio = "Professionally Devops Engineer, Wannabe Jr. SysDE, and personally terminal over-engineerer. The views expressed here are mine alone, unless they are also yours."
links = [
    { email = "mailto:hello@whits.io"},
    { github = "https://github.com/whit-colm"},
    { linkedin = "https://linkedin.com/in/whit-colm"},
    { bluesky = "https://bsky.app/profile/did:plc:jeptbfcktk2a2f4myjzqyrs3" },
    { signal-messenger = "https://signal.me/#eu/Lxqbs4b13TJkTh72_A0Fp95LtgPfr5BO2vomJVzIXb7SfpwvdahCIpNm_3MmZyjv" }
]