[[main]]
    name = "Résumé"
    url = "/docs/resume-r.pdf"
    weight = 80
    [main.params]
        icon = "file-user-solid"
        target = "_blank"

[[main]]
    name = "GitHub"
    url = "https://github.com/whit-colm"
    weight = 80
    [main.params]
        icon = "github"
        showName = false
        target = "_blank"
