[[main]]
  name = "About"
  pageRef = "/about"
  weight = 20

[[main]]
  name = "Blog"
  pageRef = "/posts"
  weight = 20

[[main]]
    name = "Education"
    url = "/edu"
    weight = 50

[[main]]
    name = "Résumé"
    url = "https://files.whits.io/resume-p.pdf"
    weight = 90
    [main.params]
        icon = "file-user-solid"
        showName = true
        target = "_blank"

[[main]]
    name = "GitHub"
    url = "https://github.com/whit-colm"
    weight = 80
    [main.params]
        icon = "github"
        showName = false
        target = "_blank"

[[footer]]
    name = "Acknowledgements"
    pageRef = "acknowledgements"
    weight = 5

[[footer]]
    name = "Security & Privacy Notes"
    pageRef = "sec-priv"
    weight = 10