colorScheme = "ocean"
defaultAppearance = "dark"
enableCodeCopy = true
enableImageWebp = true
enableRobotsTXT = true
enableSearch = false

[homepage]
  layout = "background"
  showRecent = true
  recentLimit = 4
  cardView = true
  homepageImage = "imgs/winnegance.jpg"
  layoutBackgroundBlur = true

[article]
  showDate = true
  showDateUpdated = true
  showAuthor = true
  showAuthorBottom = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  editURL = "https://github.com/whit-colm/whitsio/tree/main/content/"
  editAppendPath = true
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = false
  showComments = false

[list]
  showBreadcrumbs = true
  showSummary = false
  showTableOfContents = true
  showTaxonomies = false
  groupByYear = false
  paginationWidth = 1

[footer]
  showThemeAttribution = false
  showAppearanceSwitcher = true