baseURL = "/"
languageCode = "en-us"
title = "Whit Huntley"
theme = "hello-friend-ng"

[params]
  dateform        = "2 Jan, 2006"
  dateformShort   = "2 Jan"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Whit Huntley's Website"
  keywords = "Whit Huntley, whit colm, whitsio,"
  images = [""]

  homeSubtitle = "Seeking professional opportunities in Linux system administration and architecture, automation, and making FLOSS easily accessible and usable."

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"

  [params.favicon.color]
    mask = "#252627"
    msapplication = "#252627"
    theme = "#252627"

    [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/whitColm"

  [[params.social]]
    name = "email"
    url  = "mailto:rwx@whits.io"

  [[params.social]]
    name = "git"
    url  = "https://git.dotfile.sh/colm"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/whit-colm"

[languages]
  [languages.en]
    title = "Whit Huntley"
    subtitle = ""
    keywords = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "/home/whit/"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
    [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/blog"
  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "/projects"
  [[menu.main]]
    identifier = "resume"
    name = "Résumé"
    url = "/resume"
  [[menu.main]]
    identifier = "edu"
    name = "Education"
    url = "/edu"
